name: release NuGet package

on:
  push:
    branches: [ "main" ]
  tags:
    - v*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Add GitHub NuGet source
        run: dotnet nuget add source --username Sleeyax --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/sleeyax/index.json"
      - name: package NuGet package
        run: dotnet pack --configuration Release
      - name: push NuGet package
        run: dotnet nuget push "bin/Release/*.nupkg" --source github --api-key ${{ secrets.GITHUB_TOKEN }}
